Specify where to change the theme
catppuccin/home-assistant pull request #22
Opened 2024-10-02 02:54 UTC by Awashcard0

This was my first time installing a theme in home assistant and it had me confused looking for where the change it.

2024-11-27 19:57 UTC, DanielLemky requested changes
It was my first time adding a theme as well and the current instructions left me looking around for a bit. This addition helped.

I would just be a bit more precise with with the instructions. Something like:

7. Go to the [Profile General tab](https://my.home-assistant.io/redirect/profile) and change Theme under Browser Settings to your desired theme.

(I included the home assistant dynamic link which allows for linking to a user's profile page in their own home assistant)

2025-02-28 18:10 UTC, sgoudham commented on README.md
> +7. Go to your profile settings to pick a theme.
```suggestion
7. Go to the [Profile General tab](https://my.home-assistant.io/redirect/profile) and change Theme under Browser Settings to your desired theme.
```

2025-02-28 18:10 UTC, sgoudham commented on README.md
> +4. Go to your profile settings to pick a theme.
```suggestion
4. Go to the [Profile General tab](https://my.home-assistant.io/redirect/profile) and change Theme under Browser Settings to your desired theme.
```

2025-02-28 18:10 UTC, sgoudham approved these changes
Thanks both!

2025-02-28 18:12 UTC, merged